name: Daily Data Refresh
on:
  schedule:
    - cron: "20 16 * * *"
  workflow_dispatch:

permissions:
  contents: write  # precisa pra commitar o jobs.json

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
      ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # - run: npm install
      # - run: npm run build
      - name: Commit website/data/jobs.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add website/data/jobs.json
          git commit -m "chore: refresh jobs data" || echo "No changes"
          git push
      # - name: Send email digest (optional)
      #   if: ${{ env.SMTP_SERVER != '' }}
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: ${{ env.SMTP_SERVER }}
      #     server_port: ${{ env.SMTP_PORT }}
      #     username: ${{ env.SMTP_USERNAME }}
      #     password: ${{ env.SMTP_PASSWORD }}
      #     subject: "Daily Jobs Digest"
      #     to: ${{ env.EMAIL_TO }}
      #     from: "Jobs Tracker <${{ env.SMTP_USERNAME }}>"
      #     content_type: text/html
      #     html_body: "<h3>Novas vagas publicadas hoje</h3><p>Confere no site.</p>"
      - name: Send email digest (optional)
        if: ${{ env.SMTP_SERVER != '' }}
        run: node scripts/send_email.js
