name: Deploy website to Pages
on:
  push:
    branches: [main]
    paths:
      - 'website-react/**'  # Watch for changes in React source
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: website-react/package-lock.json
      
      - name: Install dependencies
        run: |
          cd website-react
          npm ci
      
      - name: Build React app
        run: |
          cd website-react
          npm run build
      
      - name: Copy build output to website folder
        run: |
          rm -rf website/*
          cp -r website-react/dist/* website/
          # If using build folder instead of dist:
          # cp -r website-react/build/* website/
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4